FROM ubuntu:14.04 as aosp1404
USER root
RUN groupadd -g 1001 tj \
    && useradd -d "/home/aosp" -u 1001 -g 1001 -m -s /bin/bash tj
COPY sources.list.trusty  /etc/apt/sources.list
RUN apt-get update && apt-get install -y git-core gnupg flex bison gperf build-essential \
	zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
	lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev ccache \
	libgl1-mesa-dev libxml2-utils xsltproc unzip  bc liblz4-tool rsync lzop
# install java8
ADD java-8-openjdk-amd64 /usr/lib/jvm/java-8-openjdk-amd64
RUN apt-get install -y python
#RUN apt-get clean
# install jdk7
RUN apt-get install -y openjdk-7-jdk

# fix 6.0 out/host/linux-x86/bin/jack-admin: line 27: USER: unbound variable
ENV USER tj
WORKDIR /home/aosp
USER tj


