FROM ubuntu:16.04
MAINTAINER tongjun<tj_wust@163.com>
LABEL Description="This image is the base os images which used for rk3399 linux compile"  Version="1.0"
RUN apt-get update && apt-get install -y  git vim gawk sed git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev ccache libgl1-mesa-dev libxml2-utils xsltproc unzip device-tree-compiler liblz4-tool  libfile-which-perl sed make binutils gcc g++ bash patch gzip  bzip2 perl tar cpio python unzip rsync file bc libmpc3 git  texinfo pkg-config cmake tree texinfo libssl-dev time wget openssh-server && \
	mkdir -p /var/run/sshd && \
	apt-get autoremove --purge && \
	useradd -m -s /bin/bash -d /home/tj -u 1001 -U tj && \
	echo 'tj:123456' | chgpasswd

